#!/bin/sh

convert correlation_0_age.pdf correlation_0_age.png
convert correlation_0_MJdep.pdf correlation_0_MJdep.png
convert correlation_0_sex.pdf correlation_0_sex.png
convert correlation_0_QuitYears.pdf correlation_0_QuitYears.png
convert correlation_0_MJuse.pdf correlation_0_MJuse.png
convert correlation_0_Num_Days_Drink7day.pdf correlation_0_Num_Days_Drink7day.png
convert correlation_0_QuitYears.pdf correlation_0_QuitYears.png
convert correlation_0_SmoHistory.pdf correlation_0_SmoHistory.png
convert correlation_0_SmokedYears.pdf correlation_0_SmokedYears.png
convert correlation_0_StillSmoking.pdf correlation_0_StillSmoking.png
convert correlation_0_TimeUsed.pdf correlation_0_TimeUsed.png
convert correlation_0_ToT_Drink7day.pdf correlation_0_ToT_Drink7day.png
convert correlation_0_CT_RT.pdf correlation_0_CT_RT.png
convert correlation_0_INTER_RT.pdf correlation_0_INTER_RT.png
convert correlation_0_INTER_ACC.pdf correlation_0_INTER_ACC.png
convert correlation_1_age.pdf correlation_1_age.png
convert correlation_1_MJdep.pdf correlation_1_MJdep.png
convert correlation_1_sex.pdf correlation_1_sex.png
convert correlation_1_QuitYears.pdf correlation_1_QuitYears.png
convert correlation_1_MJuse.pdf correlation_1_MJuse.png
convert correlation_1_Num_Days_Drink7day.pdf correlation_1_Num_Days_Drink7day.png
convert correlation_1_QuitYears.pdf correlation_1_QuitYears.png
convert correlation_1_SmoHistory.pdf correlation_1_SmoHistory.png
convert correlation_1_SmokedYears.pdf correlation_1_SmokedYears.png
convert correlation_1_StillSmoking.pdf correlation_1_StillSmoking.png
convert correlation_1_TimeUsed.pdf correlation_1_TimeUsed.png
convert correlation_1_ToT_Drink7day.pdf correlation_1_ToT_Drink7day.png
convert correlation_1_CT_RT.pdf correlation_1_CT_RT.png
convert correlation_1_INTER_RT.pdf correlation_1_INTER_RT.png
convert correlation_1_INTER_ACC.pdf correlation_1_INTER_ACC.png

convert correlation_2_age.pdf correlation_2_age.png
convert correlation_2_MJdep.pdf correlation_2_MJdep.png
convert correlation_2_sex.pdf correlation_2_sex.png
convert correlation_2_QuitYears.pdf correlation_2_QuitYears.png
convert correlation_2_MJuse.pdf correlation_2_MJuse.png
convert correlation_2_Num_Days_Drink7day.pdf correlation_2_Num_Days_Drink7day.png
convert correlation_2_QuitYears.pdf correlation_2_QuitYears.png
convert correlation_2_SmoHistory.pdf correlation_2_SmoHistory.png
convert correlation_2_SmokedYears.pdf correlation_2_SmokedYears.png
convert correlation_2_StillSmoking.pdf correlation_2_StillSmoking.png
convert correlation_2_TimeUsed.pdf correlation_2_TimeUsed.png
convert correlation_2_ToT_Drink7day.pdf correlation_2_ToT_Drink7day.png
convert correlation_2_CT_RT.pdf correlation_2_CT_RT.png
convert correlation_2_INTER_RT.pdf correlation_2_INTER_RT.png
convert correlation_2_INTER_ACC.pdf correlation_2_INTER_ACC.png

convert correlation_3_age.pdf correlation_3_age.png
convert correlation_3_MJdep.pdf correlation_3_MJdep.png
convert correlation_3_sex.pdf correlation_3_sex.png
convert correlation_3_QuitYears.pdf correlation_3_QuitYears.png
convert correlation_3_MJuse.pdf correlation_3_MJuse.png
convert correlation_3_Num_Days_Drink7day.pdf correlation_3_Num_Days_Drink7day.png
convert correlation_3_QuitYears.pdf correlation_3_QuitYears.png
convert correlation_3_SmoHistory.pdf correlation_3_SmoHistory.png
convert correlation_3_SmokedYears.pdf correlation_3_SmokedYears.png
convert correlation_3_StillSmoking.pdf correlation_3_StillSmoking.png
convert correlation_3_TimeUsed.pdf correlation_3_TimeUsed.png
convert correlation_3_ToT_Drink7day.pdf correlation_3_ToT_Drink7day.png
convert correlation_3_CT_RT.pdf correlation_3_CT_RT.png
convert correlation_3_INTER_RT.pdf correlation_3_INTER_RT.png
convert correlation_3_INTER_ACC.pdf correlation_3_INTER_ACC.png

convert correlation_4_age.pdf correlation_4_age.png
convert correlation_4_MJdep.pdf correlation_4_MJdep.png
convert correlation_4_sex.pdf correlation_4_sex.png
convert correlation_4_QuitYears.pdf correlation_4_QuitYears.png
convert correlation_4_MJuse.pdf correlation_4_MJuse.png
convert correlation_4_Num_Days_Drink7day.pdf correlation_4_Num_Days_Drink7day.png
convert correlation_4_QuitYears.pdf correlation_4_QuitYears.png
convert correlation_4_SmoHistory.pdf correlation_4_SmoHistory.png
convert correlation_4_SmokedYears.pdf correlation_4_SmokedYears.png
convert correlation_4_StillSmoking.pdf correlation_4_StillSmoking.png
convert correlation_4_TimeUsed.pdf correlation_4_TimeUsed.png
convert correlation_4_ToT_Drink7day.pdf correlation_4_ToT_Drink7day.png
convert correlation_4_CT_RT.pdf correlation_4_CT_RT.png
convert correlation_4_INTER_RT.pdf correlation_4_INTER_RT.png
convert correlation_4_INTER_ACC.pdf correlation_4_INTER_ACC.png

convert correlation_5_age.pdf correlation_5_age.png
convert correlation_5_MJdep.pdf correlation_5_MJdep.png
convert correlation_5_sex.pdf correlation_5_sex.png
convert correlation_5_QuitYears.pdf correlation_5_QuitYears.png
convert correlation_5_MJuse.pdf correlation_5_MJuse.png
convert correlation_5_Num_Days_Drink7day.pdf correlation_5_Num_Days_Drink7day.png
convert correlation_5_QuitYears.pdf correlation_5_QuitYears.png
convert correlation_5_SmoHistory.pdf correlation_5_SmoHistory.png
convert correlation_5_SmokedYears.pdf correlation_5_SmokedYears.png
convert correlation_5_StillSmoking.pdf correlation_5_StillSmoking.png
convert correlation_5_TimeUsed.pdf correlation_5_TimeUsed.png
convert correlation_5_ToT_Drink7day.pdf correlation_5_ToT_Drink7day.png
convert correlation_5_CT_RT.pdf correlation_5_CT_RT.png
convert correlation_5_INTER_RT.pdf correlation_5_INTER_RT.png
convert correlation_5_INTER_ACC.pdf correlation_5_INTER_ACC.png

convert correlation_6_age.pdf correlation_6_age.png
convert correlation_6_MJdep.pdf correlation_6_MJdep.png
convert correlation_6_sex.pdf correlation_6_sex.png
convert correlation_6_QuitYears.pdf correlation_6_QuitYears.png
convert correlation_6_MJuse.pdf correlation_6_MJuse.png
convert correlation_6_Num_Days_Drink7day.pdf correlation_6_Num_Days_Drink7day.png
convert correlation_6_QuitYears.pdf correlation_6_QuitYears.png
convert correlation_6_SmoHistory.pdf correlation_6_SmoHistory.png
convert correlation_6_SmokedYears.pdf correlation_6_SmokedYears.png
convert correlation_6_StillSmoking.pdf correlation_6_StillSmoking.png
convert correlation_6_TimeUsed.pdf correlation_6_TimeUsed.png
convert correlation_6_ToT_Drink7day.pdf correlation_6_ToT_Drink7day.png
convert correlation_6_CT_RT.pdf correlation_6_CT_RT.png
convert correlation_6_INTER_RT.pdf correlation_6_INTER_RT.png
convert correlation_6_INTER_ACC.pdf correlation_6_INTER_ACC.png

convert correlation_7_age.pdf correlation_7_age.png
convert correlation_7_MJdep.pdf correlation_7_MJdep.png
convert correlation_7_sex.pdf correlation_7_sex.png
convert correlation_7_QuitYears.pdf correlation_7_QuitYears.png
convert correlation_7_MJuse.pdf correlation_7_MJuse.png
convert correlation_7_Num_Days_Drink7day.pdf correlation_7_Num_Days_Drink7day.png
convert correlation_7_QuitYears.pdf correlation_7_QuitYears.png
convert correlation_7_SmoHistory.pdf correlation_7_SmoHistory.png
convert correlation_7_SmokedYears.pdf correlation_7_SmokedYears.png
convert correlation_7_StillSmoking.pdf correlation_7_StillSmoking.png
convert correlation_7_TimeUsed.pdf correlation_7_TimeUsed.png
convert correlation_7_ToT_Drink7day.pdf correlation_7_ToT_Drink7day.png
convert correlation_7_CT_RT.pdf correlation_7_CT_RT.png
convert correlation_7_INTER_RT.pdf correlation_7_INTER_RT.png
convert correlation_7_INTER_ACC.pdf correlation_7_INTER_ACC.png

convert correlation_8_age.pdf correlation_8_age.png
convert correlation_8_MJdep.pdf correlation_8_MJdep.png
convert correlation_8_sex.pdf correlation_8_sex.png
convert correlation_8_QuitYears.pdf correlation_8_QuitYears.png
convert correlation_8_MJuse.pdf correlation_8_MJuse.png
convert correlation_8_Num_Days_Drink7day.pdf correlation_8_Num_Days_Drink7day.png
convert correlation_8_QuitYears.pdf correlation_8_QuitYears.png
convert correlation_8_SmoHistory.pdf correlation_8_SmoHistory.png
convert correlation_8_SmokedYears.pdf correlation_8_SmokedYears.png
convert correlation_8_StillSmoking.pdf correlation_8_StillSmoking.png
convert correlation_8_TimeUsed.pdf correlation_8_TimeUsed.png
convert correlation_8_ToT_Drink7day.pdf correlation_8_ToT_Drink7day.png
convert correlation_8_CT_RT.pdf correlation_8_CT_RT.png
convert correlation_8_INTER_RT.pdf correlation_8_INTER_RT.png
convert correlation_8_INTER_ACC.pdf correlation_8_INTER_ACC.png

convert correlation_9_age.pdf correlation_9_age.png
convert correlation_9_MJdep.pdf correlation_9_MJdep.png
convert correlation_9_sex.pdf correlation_9_sex.png
convert correlation_9_QuitYears.pdf correlation_9_QuitYears.png
convert correlation_9_MJuse.pdf correlation_9_MJuse.png
convert correlation_9_Num_Days_Drink7day.pdf correlation_9_Num_Days_Drink7day.png
convert correlation_9_QuitYears.pdf correlation_9_QuitYears.png
convert correlation_9_SmoHistory.pdf correlation_9_SmoHistory.png
convert correlation_9_SmokedYears.pdf correlation_9_SmokedYears.png
convert correlation_9_StillSmoking.pdf correlation_9_StillSmoking.png
convert correlation_9_TimeUsed.pdf correlation_9_TimeUsed.png
convert correlation_9_ToT_Drink7day.pdf correlation_9_ToT_Drink7day.png
convert correlation_9_CT_RT.pdf correlation_9_CT_RT.png
convert correlation_9_INTER_RT.pdf correlation_9_INTER_RT.png
convert correlation_9_INTER_ACC.pdf correlation_9_INTER_ACC.png

convert correlation_10_age.pdf correlation_10_age.png
convert correlation_10_MJdep.pdf correlation_10_MJdep.png
convert correlation_10_sex.pdf correlation_10_sex.png
convert correlation_10_QuitYears.pdf correlation_10_QuitYears.png
convert correlation_10_MJuse.pdf correlation_10_MJuse.png
convert correlation_10_Num_Days_Drink7day.pdf correlation_10_Num_Days_Drink7day.png
convert correlation_10_QuitYears.pdf correlation_10_QuitYears.png
convert correlation_10_SmoHistory.pdf correlation_10_SmoHistory.png
convert correlation_10_SmokedYears.pdf correlation_10_SmokedYears.png
convert correlation_10_StillSmoking.pdf correlation_10_StillSmoking.png
convert correlation_10_TimeUsed.pdf correlation_10_TimeUsed.png
convert correlation_10_ToT_Drink7day.pdf correlation_10_ToT_Drink7day.png
convert correlation_10_CT_RT.pdf correlation_10_CT_RT.png
convert correlation_10_INTER_RT.pdf correlation_10_INTER_RT.png
convert correlation_10_INTER_ACC.pdf correlation_10_INTER_ACC.png

convert correlation_11_age.pdf correlation_11_age.png
convert correlation_11_MJdep.pdf correlation_11_MJdep.png
convert correlation_11_sex.pdf correlation_11_sex.png
convert correlation_11_QuitYears.pdf correlation_11_QuitYears.png
convert correlation_11_MJuse.pdf correlation_11_MJuse.png
convert correlation_11_Num_Days_Drink7day.pdf correlation_11_Num_Days_Drink7day.png
convert correlation_11_QuitYears.pdf correlation_11_QuitYears.png
convert correlation_11_SmoHistory.pdf correlation_11_SmoHistory.png
convert correlation_11_SmokedYears.pdf correlation_11_SmokedYears.png
convert correlation_11_StillSmoking.pdf correlation_11_StillSmoking.png
convert correlation_11_TimeUsed.pdf correlation_11_TimeUsed.png
convert correlation_11_ToT_Drink7day.pdf correlation_11_ToT_Drink7day.png
convert correlation_11_CT_RT.pdf correlation_11_CT_RT.png
convert correlation_11_INTER_RT.pdf correlation_11_INTER_RT.png
convert correlation_11_INTER_ACC.pdf correlation_11_INTER_ACC.png

convert correlation_12_age.pdf correlation_12_age.png
convert correlation_12_MJdep.pdf correlation_12_MJdep.png
convert correlation_12_sex.pdf correlation_12_sex.png
convert correlation_12_QuitYears.pdf correlation_12_QuitYears.png
convert correlation_12_MJuse.pdf correlation_12_MJuse.png
convert correlation_12_Num_Days_Drink7day.pdf correlation_12_Num_Days_Drink7day.png
convert correlation_12_QuitYears.pdf correlation_12_QuitYears.png
convert correlation_12_SmoHistory.pdf correlation_12_SmoHistory.png
convert correlation_12_SmokedYears.pdf correlation_12_SmokedYears.png
convert correlation_12_StillSmoking.pdf correlation_12_StillSmoking.png
convert correlation_12_TimeUsed.pdf correlation_12_TimeUsed.png
convert correlation_12_ToT_Drink7day.pdf correlation_12_ToT_Drink7day.png
convert correlation_12_CT_RT.pdf correlation_12_CT_RT.png
convert correlation_12_INTER_RT.pdf correlation_12_INTER_RT.png
convert correlation_12_INTER_ACC.pdf correlation_12_INTER_ACC.png

convert correlation_13_age.pdf correlation_13_age.png
convert correlation_13_MJdep.pdf correlation_13_MJdep.png
convert correlation_13_sex.pdf correlation_13_sex.png
convert correlation_13_QuitYears.pdf correlation_13_QuitYears.png
convert correlation_13_MJuse.pdf correlation_13_MJuse.png
convert correlation_13_Num_Days_Drink7day.pdf correlation_13_Num_Days_Drink7day.png
convert correlation_13_QuitYears.pdf correlation_13_QuitYears.png
convert correlation_13_SmoHistory.pdf correlation_13_SmoHistory.png
convert correlation_13_SmokedYears.pdf correlation_13_SmokedYears.png
convert correlation_13_StillSmoking.pdf correlation_13_StillSmoking.png
convert correlation_13_TimeUsed.pdf correlation_13_TimeUsed.png
convert correlation_13_ToT_Drink7day.pdf correlation_13_ToT_Drink7day.png
convert correlation_13_CT_RT.pdf correlation_13_CT_RT.png
convert correlation_13_INTER_RT.pdf correlation_13_INTER_RT.png
convert correlation_13_INTER_ACC.pdf correlation_13_INTER_ACC.png

convert correlation_14_age.pdf correlation_14_age.png
convert correlation_14_MJdep.pdf correlation_14_MJdep.png
convert correlation_14_sex.pdf correlation_14_sex.png
convert correlation_14_QuitYears.pdf correlation_14_QuitYears.png
convert correlation_14_MJuse.pdf correlation_14_MJuse.png
convert correlation_14_Num_Days_Drink7day.pdf correlation_14_Num_Days_Drink7day.png
convert correlation_14_QuitYears.pdf correlation_14_QuitYears.png
convert correlation_14_SmoHistory.pdf correlation_14_SmoHistory.png
convert correlation_14_SmokedYears.pdf correlation_14_SmokedYears.png
convert correlation_14_StillSmoking.pdf correlation_14_StillSmoking.png
convert correlation_14_TimeUsed.pdf correlation_14_TimeUsed.png
convert correlation_14_ToT_Drink7day.pdf correlation_14_ToT_Drink7day.png
convert correlation_14_CT_RT.pdf correlation_14_CT_RT.png
convert correlation_14_INTER_RT.pdf correlation_14_INTER_RT.png
convert correlation_14_INTER_ACC.pdf correlation_14_INTER_ACC.png

convert correlation_15_age.pdf correlation_15_age.png
convert correlation_15_MJdep.pdf correlation_15_MJdep.png
convert correlation_15_sex.pdf correlation_15_sex.png
convert correlation_15_QuitYears.pdf correlation_15_QuitYears.png
convert correlation_15_MJuse.pdf correlation_15_MJuse.png
convert correlation_15_Num_Days_Drink7day.pdf correlation_15_Num_Days_Drink7day.png
convert correlation_15_QuitYears.pdf correlation_15_QuitYears.png
convert correlation_15_SmoHistory.pdf correlation_15_SmoHistory.png
convert correlation_15_SmokedYears.pdf correlation_15_SmokedYears.png
convert correlation_15_StillSmoking.pdf correlation_15_StillSmoking.png
convert correlation_15_TimeUsed.pdf correlation_15_TimeUsed.png
convert correlation_15_ToT_Drink7day.pdf correlation_15_ToT_Drink7day.png
convert correlation_15_CT_RT.pdf correlation_15_CT_RT.png
convert correlation_15_INTER_RT.pdf correlation_15_INTER_RT.png
convert correlation_15_INTER_ACC.pdf correlation_15_INTER_ACC.png

convert correlation_16_age.pdf correlation_16_age.png
convert correlation_16_MJdep.pdf correlation_16_MJdep.png
convert correlation_16_sex.pdf correlation_16_sex.png
convert correlation_16_QuitYears.pdf correlation_16_QuitYears.png
convert correlation_16_MJuse.pdf correlation_16_MJuse.png
convert correlation_16_Num_Days_Drink7day.pdf correlation_16_Num_Days_Drink7day.png
convert correlation_16_QuitYears.pdf correlation_16_QuitYears.png
convert correlation_16_SmoHistory.pdf correlation_16_SmoHistory.png
convert correlation_16_INTER_ACC.pdf correlation_16_INTER_ACC.png
convert correlation_17_age.pdf correlation_17_age.png
convert correlation_17_MJdep.pdf correlation_17_MJdep.png
convert correlation_17_sex.pdf correlation_17_sex.png
convert correlation_17_QuitYears.pdf correlation_17_QuitYears.png
convert correlation_17_MJuse.pdf correlation_17_MJuse.png
convert correlation_17_Num_Days_Drink7day.pdf correlation_17_Num_Days_Drink7day.png
convert correlation_17_QuitYears.pdf correlation_17_QuitYears.png
convert correlation_17_SmoHistory.pdf correlation_17_SmoHistory.png
convert correlation_17_INTER_ACC.pdf correlation_17_INTER_ACC.png
convert correlation_18_age.pdf correlation_18_age.png
convert correlation_18_MJdep.pdf correlation_18_MJdep.png
convert correlation_18_sex.pdf correlation_18_sex.png
convert correlation_18_QuitYears.pdf correlation_18_QuitYears.png
convert correlation_18_MJuse.pdf correlation_18_MJuse.png
convert correlation_18_Num_Days_Drink7day.pdf correlation_18_Num_Days_Drink7day.png
convert correlation_18_QuitYears.pdf correlation_18_QuitYears.png
convert correlation_18_SmoHistory.pdf correlation_18_SmoHistory.png
convert correlation_18_INTER_ACC.pdf correlation_18_INTER_ACC.png
convert correlation_19_age.pdf correlation_19_age.png
convert correlation_19_MJdep.pdf correlation_19_MJdep.png
convert correlation_19_sex.pdf correlation_19_sex.png
convert correlation_19_QuitYears.pdf correlation_19_QuitYears.png
convert correlation_19_MJuse.pdf correlation_19_MJuse.png
convert correlation_19_Num_Days_Drink7day.pdf correlation_19_Num_Days_Drink7day.png
convert correlation_19_QuitYears.pdf correlation_19_QuitYears.png
convert correlation_19_SmoHistory.pdf correlation_19_SmoHistory.png
convert correlation_19_INTER_ACC.pdf correlation_19_INTER_ACC.png
convert correlation_21_MJdep.pdf correlation_21_MJdep.png
convert correlation_21_sex.pdf correlation_21_sex.png
convert correlation_21_QuitYears.pdf correlation_21_QuitYears.png
convert correlation_21_MJuse.pdf correlation_21_MJuse.png
convert correlation_21_Num_Days_Drink7day.pdf correlation_21_Num_Days_Drink7day.png
convert correlation_21_QuitYears.pdf correlation_21_QuitYears.png
convert correlation_21_SmoHistory.pdf correlation_21_SmoHistory.png
convert correlation_21_INTER_ACC.pdf correlation_21_INTER_ACC.png
convert correlation_21_age.pdf correlation_21_age.png
convert correlation_21_MJdep.pdf correlation_21_MJdep.png
convert correlation_21_sex.pdf correlation_21_sex.png
convert correlation_21_QuitYears.pdf correlation_21_QuitYears.png
convert correlation_21_MJuse.pdf correlation_21_MJuse.png
convert correlation_21_Num_Days_Drink7day.pdf correlation_21_Num_Days_Drink7day.png
convert correlation_21_QuitYears.pdf correlation_21_QuitYears.png
convert correlation_21_PP.pdf correlation_21_PP.png
convert correlation_22_age.pdf correlation_22_age.png
convert correlation_22_MJdep.pdf correlation_22_MJdep.png
convert correlation_22_sex.pdf correlation_22_sex.png
convert correlation_22_QuitYears.pdf correlation_22_QuitYears.png
convert correlation_22_MJuse.pdf correlation_22_MJuse.png
convert correlation_22_Num_Days_Drink7day.pdf correlation_22_Num_Days_Drink7day.png
convert correlation_22_QuitYears.pdf correlation_22_QuitYears.png
convert correlation_22_PP.pdf correlation_22_PP.png
convert correlation_23_age.pdf correlation_23_age.png
convert correlation_23_MJdep.pdf correlation_23_MJdep.png
convert correlation_23_sex.pdf correlation_23_sex.png
convert correlation_23_QuitYears.pdf correlation_23_QuitYears.png
convert correlation_23_MJuse.pdf correlation_23_MJuse.png
convert correlation_23_Num_Days_Drink7day.pdf correlation_23_Num_Days_Drink7day.png
convert correlation_23_QuitYears.pdf correlation_23_QuitYears.png
convert correlation_23_PP.pdf correlation_23_PP.png
convert correlation_24_age.pdf correlation_24_age.png
convert correlation_24_MJdep.pdf correlation_24_MJdep.png
convert correlation_24_sex.pdf correlation_24_sex.png
convert correlation_24_QuitYears.pdf correlation_24_QuitYears.png
convert correlation_24_MJuse.pdf correlation_24_MJuse.png
convert correlation_24_Num_Days_Drink7day.pdf correlation_24_Num_Days_Drink7day.png
convert correlation_24_QuitYears.pdf correlation_24_QuitYears.png
convert correlation_24_PP.pdf correlation_24_PP.png
convert correlation_25_age.pdf correlation_25_age.png
convert correlation_25_MJdep.pdf correlation_25_MJdep.png
convert correlation_25_sex.pdf correlation_25_sex.png
convert correlation_25_QuitYears.pdf correlation_25_QuitYears.png
convert correlation_25_MJuse.pdf correlation_25_MJuse.png
convert correlation_25_Num_Days_Drink7day.pdf correlation_25_Num_Days_Drink7day.png
convert correlation_25_QuitYears.pdf correlation_25_QuitYears.png
convert correlation_25_PP.pdf correlation_25_PP.png
convert correlation_26_age.pdf correlation_26_age.png
convert correlation_26_MJdep.pdf correlation_26_MJdep.png
convert correlation_26_sex.pdf correlation_26_sex.png
convert correlation_26_QuitYears.pdf correlation_26_QuitYears.png
convert correlation_26_MJuse.pdf correlation_26_MJuse.png
convert correlation_26_Num_Days_Drink7day.pdf correlation_26_Num_Days_Drink7day.png
convert correlation_26_QuitYears.pdf correlation_26_QuitYears.png
convert correlation_26_PP.pdf correlation_26_PP.png
convert correlation_27_age.pdf correlation_27_age.png
convert correlation_27_MJdep.pdf correlation_27_MJdep.png
convert correlation_27_sex.pdf correlation_27_sex.png
convert correlation_27_QuitYears.pdf correlation_27_QuitYears.png
convert correlation_27_MJuse.pdf correlation_27_MJuse.png
convert correlation_27_Num_Days_Drink7day.pdf correlation_27_Num_Days_Drink7day.png
convert correlation_27_QuitYears.pdf correlation_27_QuitYears.png
convert correlation_27_PP.pdf correlation_27_PP.png
convert correlation_28_age.pdf correlation_28_age.png
convert correlation_28_MJdep.pdf correlation_28_MJdep.png
convert correlation_28_sex.pdf correlation_28_sex.png
convert correlation_28_QuitYears.pdf correlation_28_QuitYears.png
convert correlation_28_MJuse.pdf correlation_28_MJuse.png
convert correlation_28_Num_Days_Drink7day.pdf correlation_28_Num_Days_Drink7day.png
convert correlation_28_QuitYears.pdf correlation_28_QuitYears.png
convert correlation_28_PP.pdf correlation_28_PP.png
convert correlation_29_age.pdf correlation_29_age.png
convert correlation_29_MJdep.pdf correlation_29_MJdep.png
convert correlation_29_sex.pdf correlation_29_sex.png
convert correlation_29_QuitYears.pdf correlation_29_QuitYears.png
convert correlation_29_MJuse.pdf correlation_29_MJuse.png
convert correlation_29_Num_Days_Drink7day.pdf correlation_29_Num_Days_Drink7day.png
convert correlation_29_QuitYears.pdf correlation_29_QuitYears.png
convert correlation_29_PP.pdf correlation_29_PP.png
# convert correlation_31_MJdep.pdf correlation_31_MJdep.png
# convert correlation_31_sex.pdf correlation_31_sex.png
# convert correlation_31_QuitYears.pdf correlation_31_QuitYears.png
# convert correlation_31_MJuse.pdf correlation_31_MJuse.png
# convert correlation_31_Num_Days_Drink7day.pdf correlation_31_Num_Days_Drink7day.png
# convert correlation_31_QuitYears.pdf correlation_31_QuitYears.png
# convert correlation_31_PP.pdf correlation_31_PP.png
# convert correlation_31_age.pdf correlation_33_age.png
# convert correlation_31_MJdep.pdf correlation_31_MJdep.png
# convert correlation_31_sex.pdf correlation_31_sex.png
# convert correlation_31_QuitYears.pdf correlation_31_QuitYears.png
# convert correlation_31_MJuse.pdf correlation_31_MJuse.png
# convert correlation_31_Num_Days_Drink7day.pdf correlation_31_Num_Days_Drink7day.png
# convert correlation_31_QuitYears.pdf correlation_31_QuitYears.png
# convert correlation_31_PP.pdf correlation_31_PP.png
# convert correlation_32_age.pdf correlation_32_age.png
# convert correlation_32_MJdep.pdf correlation_32_MJdep.png
# convert correlation_32_sex.pdf correlation_32_sex.png
# convert correlation_32_QuitYears.pdf correlation_32_QuitYears.png
# convert correlation_32_MJuse.pdf correlation_32_MJuse.png
# convert correlation_32_Num_Days_Drink7day.pdf correlation_32_Num_Days_Drink7day.png
# convert correlation_32_QuitYears.pdf correlation_32_QuitYears.png
# convert correlation_32_PP.pdf correlation_32_PP.png
# convert correlation_33_age.pdf correlation_33_age.png
# convert correlation_33_MJdep.pdf correlation_33_MJdep.png
# convert correlation_33_sex.pdf correlation_33_sex.png
# convert correlation_33_QuitYears.pdf correlation_33_QuitYears.png
# convert correlation_33_MJuse.pdf correlation_33_MJuse.png
# convert correlation_33_Num_Days_Drink7day.pdf correlation_33_Num_Days_Drink7day.png
# convert correlation_33_QuitYears.pdf correlation_33_QuitYears.png
# convert correlation_33_PP.pdf correlation_33_PP.png
# convert correlation_34_age.pdf correlation_34_age.png
# convert correlation_34_MJdep.pdf correlation_34_MJdep.png
# convert correlation_34_sex.pdf correlation_34_sex.png
# convert correlation_34_QuitYears.pdf correlation_34_QuitYears.png
# convert correlation_34_MJuse.pdf correlation_34_MJuse.png
# convert correlation_34_Num_Days_Drink7day.pdf correlation_34_Num_Days_Drink7day.png
# convert correlation_34_QuitYears.pdf correlation_34_QuitYears.png
# convert correlation_34_PP.pdf correlation_34_PP.png
# convert correlation_35_age.pdf correlation_35_age.png
# convert correlation_35_MJdep.pdf correlation_35_MJdep.png
# convert correlation_35_sex.pdf correlation_35_sex.png
# convert correlation_35_QuitYears.pdf correlation_35_QuitYears.png
# convert correlation_35_MJuse.pdf correlation_35_MJuse.png
# convert correlation_35_Num_Days_Drink7day.pdf correlation_35_Num_Days_Drink7day.png
# convert correlation_35_QuitYears.pdf correlation_35_QuitYears.png
# convert correlation_35_PP.pdf correlation_35_PP.png
# convert correlation_36_age.pdf correlation_36_age.png
# convert correlation_36_MJdep.pdf correlation_36_MJdep.png
# convert correlation_36_sex.pdf correlation_36_sex.png
# convert correlation_36_QuitYears.pdf correlation_36_QuitYears.png
# convert correlation_36_MJuse.pdf correlation_36_MJuse.png
# convert correlation_36_Num_Days_Drink7day.pdf correlation_36_Num_Days_Drink7day.png
# convert correlation_36_QuitYears.pdf correlation_36_QuitYears.png
# convert correlation_36_PP.pdf correlation_36_PP.png
# convert correlation_37_age.pdf correlation_37_age.png
# convert correlation_37_MJdep.pdf correlation_37_MJdep.png
# convert correlation_37_sex.pdf correlation_37_sex.png
# convert correlation_37_QuitYears.pdf correlation_37_QuitYears.png
# convert correlation_37_MJuse.pdf correlation_37_MJuse.png
# convert correlation_37_Num_Days_Drink7day.pdf correlation_37_Num_Days_Drink7day.png
# convert correlation_37_QuitYears.pdf correlation_37_QuitYears.png
# convert correlation_37_PP.pdf correlation_37_PP.png
# convert correlation_38_age.pdf correlation_38_age.png
# convert correlation_38_MJdep.pdf correlation_38_MJdep.png
# convert correlation_38_sex.pdf correlation_38_sex.png
# convert correlation_38_QuitYears.pdf correlation_38_QuitYears.png
# convert correlation_38_MJuse.pdf correlation_38_MJuse.png
# convert correlation_38_Num_Days_Drink7day.pdf correlation_38_Num_Days_Drink7day.png
# convert correlation_38_QuitYears.pdf correlation_38_QuitYears.png
# convert correlation_38_PP.pdf correlation_38_PP.png
# convert correlation_39_age.pdf correlation_39_age.png
# convert correlation_39_MJdep.pdf correlation_39_MJdep.png
# convert correlation_39_sex.pdf correlation_39_sex.png
# convert correlation_39_QuitYears.pdf correlation_39_QuitYears.png
# convert correlation_39_MJuse.pdf correlation_39_MJuse.png
# convert correlation_39_Num_Days_Drink7day.pdf correlation_39_Num_Days_Drink7day.png
# convert correlation_39_QuitYears.pdf correlation_39_QuitYears.png
# convert correlation_39_PP.pdf correlation_39_PP.png