#!/bin/sh

convert correlation_0_age.eps correlation_0_age.png
convert correlation_0_ToT_Drink7day.eps correlation_0_ToT_Drink7day.png
convert correlation_0_sex.eps correlation_0_sex.png
convert correlation_0_Num_Days_Drink7day.eps correlation_0_Num_Days_Drink7day.png
convert correlation_0_SmoHistory.eps correlation_0_SmoHistory.png
convert correlation_0_StillSmoking.eps correlation_0_StillSmoking.png
convert correlation_0_QuitYears.eps correlation_0_QuitYears.png
convert correlation_0_SmokedYears.eps correlation_0_SmokedYears.png
convert correlation_0_MJuse.eps correlation_0_MJuse.png
convert correlation_0_MJdep.eps correlation_0_MJdep.png
convert correlation_0_MJonset.eps correlation_0_MJonset.png
convert correlation_0_TimeUsed.eps correlation_0_TimeUsed.png
convert correlation_0_CT_RT.eps correlation_0_CT_RT.png
convert correlation_0_INTER_RT.eps correlation_0_INTER_RT.png
convert correlation_0_INTER_ACC.eps correlation_0_INTER_ACC.png
convert correlation_1_age.eps correlation_1_age.png
convert correlation_1_ToT_Drink7day.eps correlation_1_ToT_Drink7day.png
convert correlation_1_sex.eps correlation_1_sex.png
convert correlation_1_Num_Days_Drink7day.eps correlation_1_Num_Days_Drink7day.png
convert correlation_1_SmoHistory.eps correlation_1_SmoHistory.png
convert correlation_1_StillSmoking.eps correlation_1_StillSmoking.png
convert correlation_1_QuitYears.eps correlation_1_QuitYears.png
convert correlation_1_SmokedYears.eps correlation_1_SmokedYears.png
convert correlation_1_MJuse.eps correlation_1_MJuse.png
convert correlation_1_MJdep.eps correlation_1_MJdep.png
convert correlation_1_MJonset.eps correlation_1_MJonset.png
convert correlation_1_TimeUsed.eps correlation_1_TimeUsed.png
convert correlation_1_CT_RT.eps correlation_1_CT_RT.png
convert correlation_1_INTER_RT.eps correlation_1_INTER_RT.png
convert correlation_1_INTER_ACC.eps correlation_1_INTER_ACC.png

convert correlation_2_age.eps correlation_2_age.png
convert correlation_2_ToT_Drink7day.eps correlation_2_ToT_Drink7day.png
convert correlation_2_sex.eps correlation_2_sex.png
convert correlation_2_Num_Days_Drink7day.eps correlation_2_Num_Days_Drink7day.png
convert correlation_2_SmoHistory.eps correlation_2_SmoHistory.png
convert correlation_2_StillSmoking.eps correlation_2_StillSmoking.png
convert correlation_2_QuitYears.eps correlation_2_QuitYears.png
convert correlation_2_SmokedYears.eps correlation_2_SmokedYears.png
convert correlation_2_MJuse.eps correlation_2_MJuse.png
convert correlation_2_MJdep.eps correlation_2_MJdep.png
convert correlation_2_MJonset.eps correlation_2_MJonset.png
convert correlation_2_TimeUsed.eps correlation_2_TimeUsed.png
convert correlation_2_CT_RT.eps correlation_2_CT_RT.png
convert correlation_2_INTER_RT.eps correlation_2_INTER_RT.png
convert correlation_2_INTER_ACC.eps correlation_2_INTER_ACC.png

convert correlation_3_age.eps correlation_3_age.png
convert correlation_3_ToT_Drink7day.eps correlation_3_ToT_Drink7day.png
convert correlation_3_sex.eps correlation_3_sex.png
convert correlation_3_Num_Days_Drink7day.eps correlation_3_Num_Days_Drink7day.png
convert correlation_3_SmoHistory.eps correlation_3_SmoHistory.png
convert correlation_3_StillSmoking.eps correlation_3_StillSmoking.png
convert correlation_3_QuitYears.eps correlation_3_QuitYears.png
convert correlation_3_SmokedYears.eps correlation_3_SmokedYears.png
convert correlation_3_MJuse.eps correlation_3_MJuse.png
convert correlation_3_MJdep.eps correlation_3_MJdep.png
convert correlation_3_MJonset.eps correlation_3_MJonset.png
convert correlation_3_TimeUsed.eps correlation_3_TimeUsed.png
convert correlation_3_CT_RT.eps correlation_3_CT_RT.png
convert correlation_3_INTER_RT.eps correlation_3_INTER_RT.png
convert correlation_3_INTER_ACC.eps correlation_3_INTER_ACC.png

convert correlation_4_age.eps correlation_4_age.png
convert correlation_4_ToT_Drink7day.eps correlation_4_ToT_Drink7day.png
convert correlation_4_sex.eps correlation_4_sex.png
convert correlation_4_Num_Days_Drink7day.eps correlation_4_Num_Days_Drink7day.png
convert correlation_4_SmoHistory.eps correlation_4_SmoHistory.png
convert correlation_4_StillSmoking.eps correlation_4_StillSmoking.png
convert correlation_4_QuitYears.eps correlation_4_QuitYears.png
convert correlation_4_SmokedYears.eps correlation_4_SmokedYears.png
convert correlation_4_MJuse.eps correlation_4_MJuse.png
convert correlation_4_MJdep.eps correlation_4_MJdep.png
convert correlation_4_MJonset.eps correlation_4_MJonset.png
convert correlation_4_TimeUsed.eps correlation_4_TimeUsed.png
convert correlation_4_CT_RT.eps correlation_4_CT_RT.png
convert correlation_4_INTER_RT.eps correlation_4_INTER_RT.png
convert correlation_4_INTER_ACC.eps correlation_4_INTER_ACC.png

convert correlation_5_age.eps correlation_5_age.png
convert correlation_5_ToT_Drink7day.eps correlation_5_ToT_Drink7day.png
convert correlation_5_sex.eps correlation_5_sex.png
convert correlation_5_Num_Days_Drink7day.eps correlation_5_Num_Days_Drink7day.png
convert correlation_5_SmoHistory.eps correlation_5_SmoHistory.png
convert correlation_5_StillSmoking.eps correlation_5_StillSmoking.png
convert correlation_5_QuitYears.eps correlation_5_QuitYears.png
convert correlation_5_SmokedYears.eps correlation_5_SmokedYears.png
convert correlation_5_MJuse.eps correlation_5_MJuse.png
convert correlation_5_MJdep.eps correlation_5_MJdep.png
convert correlation_5_MJonset.eps correlation_5_MJonset.png
convert correlation_5_TimeUsed.eps correlation_5_TimeUsed.png
convert correlation_5_CT_RT.eps correlation_5_CT_RT.png
convert correlation_5_INTER_RT.eps correlation_5_INTER_RT.png
convert correlation_5_INTER_ACC.eps correlation_5_INTER_ACC.png

convert correlation_6_age.eps correlation_6_age.png
convert correlation_6_ToT_Drink7day.eps correlation_6_ToT_Drink7day.png
convert correlation_6_sex.eps correlation_6_sex.png
convert correlation_6_Num_Days_Drink7day.eps correlation_6_Num_Days_Drink7day.png
convert correlation_6_SmoHistory.eps correlation_6_SmoHistory.png
convert correlation_6_StillSmoking.eps correlation_6_StillSmoking.png
convert correlation_6_QuitYears.eps correlation_6_QuitYears.png
convert correlation_6_SmokedYears.eps correlation_6_SmokedYears.png
convert correlation_6_MJuse.eps correlation_6_MJuse.png
convert correlation_6_MJdep.eps correlation_6_MJdep.png
convert correlation_6_MJonset.eps correlation_6_MJonset.png
convert correlation_6_TimeUsed.eps correlation_6_TimeUsed.png
convert correlation_6_CT_RT.eps correlation_6_CT_RT.png
convert correlation_6_INTER_RT.eps correlation_6_INTER_RT.png
convert correlation_6_INTER_ACC.eps correlation_6_INTER_ACC.png

convert correlation_7_age.eps correlation_7_age.png
convert correlation_7_ToT_Drink7day.eps correlation_7_ToT_Drink7day.png
convert correlation_7_sex.eps correlation_7_sex.png
convert correlation_7_Num_Days_Drink7day.eps correlation_7_Num_Days_Drink7day.png
convert correlation_7_SmoHistory.eps correlation_7_SmoHistory.png
convert correlation_7_StillSmoking.eps correlation_7_StillSmoking.png
convert correlation_7_QuitYears.eps correlation_7_QuitYears.png
convert correlation_7_SmokedYears.eps correlation_7_SmokedYears.png
convert correlation_7_MJuse.eps correlation_7_MJuse.png
convert correlation_7_MJdep.eps correlation_7_MJdep.png
convert correlation_7_MJonset.eps correlation_7_MJonset.png
convert correlation_7_TimeUsed.eps correlation_7_TimeUsed.png
convert correlation_7_CT_RT.eps correlation_7_CT_RT.png
convert correlation_7_INTER_RT.eps correlation_7_INTER_RT.png
convert correlation_7_INTER_ACC.eps correlation_7_INTER_ACC.png

convert correlation_8_age.eps correlation_8_age.png
convert correlation_8_ToT_Drink7day.eps correlation_8_ToT_Drink7day.png
convert correlation_8_sex.eps correlation_8_sex.png
convert correlation_8_Num_Days_Drink7day.eps correlation_8_Num_Days_Drink7day.png
convert correlation_8_SmoHistory.eps correlation_8_SmoHistory.png
convert correlation_8_StillSmoking.eps correlation_8_StillSmoking.png
convert correlation_8_QuitYears.eps correlation_8_QuitYears.png
convert correlation_8_SmokedYears.eps correlation_8_SmokedYears.png
convert correlation_8_MJuse.eps correlation_8_MJuse.png
convert correlation_8_MJdep.eps correlation_8_MJdep.png
convert correlation_8_MJonset.eps correlation_8_MJonset.png
convert correlation_8_TimeUsed.eps correlation_8_TimeUsed.png
convert correlation_8_CT_RT.eps correlation_8_CT_RT.png
convert correlation_8_INTER_RT.eps correlation_8_INTER_RT.png
convert correlation_8_INTER_ACC.eps correlation_8_INTER_ACC.png

convert correlation_9_age.eps correlation_9_age.png
convert correlation_9_ToT_Drink7day.eps correlation_9_ToT_Drink7day.png
convert correlation_9_sex.eps correlation_9_sex.png
convert correlation_9_Num_Days_Drink7day.eps correlation_9_Num_Days_Drink7day.png
convert correlation_9_SmoHistory.eps correlation_9_SmoHistory.png
convert correlation_9_StillSmoking.eps correlation_9_StillSmoking.png
convert correlation_9_QuitYears.eps correlation_9_QuitYears.png
convert correlation_9_SmokedYears.eps correlation_9_SmokedYears.png
convert correlation_9_MJuse.eps correlation_9_MJuse.png
convert correlation_9_MJdep.eps correlation_9_MJdep.png
convert correlation_9_MJonset.eps correlation_9_MJonset.png
convert correlation_9_TimeUsed.eps correlation_9_TimeUsed.png
convert correlation_9_CT_RT.eps correlation_9_CT_RT.png
convert correlation_9_INTER_RT.eps correlation_9_INTER_RT.png
convert correlation_9_INTER_ACC.eps correlation_9_INTER_ACC.png

convert correlation_10_age.eps correlation_10_age.png
convert correlation_10_ToT_Drink7day.eps correlation_10_ToT_Drink7day.png
convert correlation_10_sex.eps correlation_10_sex.png
convert correlation_10_Num_Days_Drink7day.eps correlation_10_Num_Days_Drink7day.png
convert correlation_10_SmoHistory.eps correlation_10_SmoHistory.png
convert correlation_10_StillSmoking.eps correlation_10_StillSmoking.png
convert correlation_10_QuitYears.eps correlation_10_QuitYears.png
convert correlation_10_SmokedYears.eps correlation_10_SmokedYears.png
convert correlation_10_MJuse.eps correlation_10_MJuse.png
convert correlation_10_MJdep.eps correlation_10_MJdep.png
convert correlation_10_MJonset.eps correlation_10_MJonset.png
convert correlation_10_TimeUsed.eps correlation_10_TimeUsed.png
convert correlation_10_CT_RT.eps correlation_10_CT_RT.png
convert correlation_10_INTER_RT.eps correlation_10_INTER_RT.png
convert correlation_10_INTER_ACC.eps correlation_10_INTER_ACC.png

convert correlation_11_age.eps correlation_11_age.png
convert correlation_11_ToT_Drink7day.eps correlation_11_ToT_Drink7day.png
convert correlation_11_sex.eps correlation_11_sex.png
convert correlation_11_Num_Days_Drink7day.eps correlation_11_Num_Days_Drink7day.png
convert correlation_11_SmoHistory.eps correlation_11_SmoHistory.png
convert correlation_11_StillSmoking.eps correlation_11_StillSmoking.png
convert correlation_11_QuitYears.eps correlation_11_QuitYears.png
convert correlation_11_SmokedYears.eps correlation_11_SmokedYears.png
convert correlation_11_MJuse.eps correlation_11_MJuse.png
convert correlation_11_MJdep.eps correlation_11_MJdep.png
convert correlation_11_MJonset.eps correlation_11_MJonset.png
convert correlation_11_TimeUsed.eps correlation_11_TimeUsed.png
convert correlation_11_CT_RT.eps correlation_11_CT_RT.png
convert correlation_11_INTER_RT.eps correlation_11_INTER_RT.png
convert correlation_11_INTER_ACC.eps correlation_11_INTER_ACC.png

convert correlation_12_age.eps correlation_12_age.png
convert correlation_12_ToT_Drink7day.eps correlation_12_ToT_Drink7day.png
convert correlation_12_sex.eps correlation_12_sex.png
convert correlation_12_Num_Days_Drink7day.eps correlation_12_Num_Days_Drink7day.png
convert correlation_12_SmoHistory.eps correlation_12_SmoHistory.png
convert correlation_12_StillSmoking.eps correlation_12_StillSmoking.png
convert correlation_12_QuitYears.eps correlation_12_QuitYears.png
convert correlation_12_SmokedYears.eps correlation_12_SmokedYears.png
convert correlation_12_MJuse.eps correlation_12_MJuse.png
convert correlation_12_MJdep.eps correlation_12_MJdep.png
convert correlation_12_MJonset.eps correlation_12_MJonset.png
convert correlation_12_TimeUsed.eps correlation_12_TimeUsed.png
convert correlation_12_CT_RT.eps correlation_12_CT_RT.png
convert correlation_12_INTER_RT.eps correlation_12_INTER_RT.png
convert correlation_12_INTER_ACC.eps correlation_12_INTER_ACC.png

convert correlation_13_age.eps correlation_13_age.png
convert correlation_13_ToT_Drink7day.eps correlation_13_ToT_Drink7day.png
convert correlation_13_sex.eps correlation_13_sex.png
convert correlation_13_Num_Days_Drink7day.eps correlation_13_Num_Days_Drink7day.png
convert correlation_13_SmoHistory.eps correlation_13_SmoHistory.png
convert correlation_13_StillSmoking.eps correlation_13_StillSmoking.png
convert correlation_13_QuitYears.eps correlation_13_QuitYears.png
convert correlation_13_SmokedYears.eps correlation_13_SmokedYears.png
convert correlation_13_MJuse.eps correlation_13_MJuse.png
convert correlation_13_MJdep.eps correlation_13_MJdep.png
convert correlation_13_MJonset.eps correlation_13_MJonset.png
convert correlation_13_TimeUsed.eps correlation_13_TimeUsed.png
convert correlation_13_CT_RT.eps correlation_13_CT_RT.png
convert correlation_13_INTER_RT.eps correlation_13_INTER_RT.png
convert correlation_13_INTER_ACC.eps correlation_13_INTER_ACC.png

convert correlation_14_age.eps correlation_14_age.png
convert correlation_14_ToT_Drink7day.eps correlation_14_ToT_Drink7day.png
convert correlation_14_sex.eps correlation_14_sex.png
convert correlation_14_Num_Days_Drink7day.eps correlation_14_Num_Days_Drink7day.png
convert correlation_14_SmoHistory.eps correlation_14_SmoHistory.png
convert correlation_14_StillSmoking.eps correlation_14_StillSmoking.png
convert correlation_14_QuitYears.eps correlation_14_QuitYears.png
convert correlation_14_SmokedYears.eps correlation_14_SmokedYears.png
convert correlation_14_MJuse.eps correlation_14_MJuse.png
convert correlation_14_MJdep.eps correlation_14_MJdep.png
convert correlation_14_MJonset.eps correlation_14_MJonset.png
convert correlation_14_TimeUsed.eps correlation_14_TimeUsed.png
convert correlation_14_CT_RT.eps correlation_14_CT_RT.png
convert correlation_14_INTER_RT.eps correlation_14_INTER_RT.png
convert correlation_14_INTER_ACC.eps correlation_14_INTER_ACC.png

convert correlation_15_age.eps correlation_15_age.png
convert correlation_15_ToT_Drink7day.eps correlation_15_ToT_Drink7day.png
convert correlation_15_sex.eps correlation_15_sex.png
convert correlation_15_Num_Days_Drink7day.eps correlation_15_Num_Days_Drink7day.png
convert correlation_15_SmoHistory.eps correlation_15_SmoHistory.png
convert correlation_15_StillSmoking.eps correlation_15_StillSmoking.png
convert correlation_15_QuitYears.eps correlation_15_QuitYears.png
convert correlation_15_SmokedYears.eps correlation_15_SmokedYears.png
convert correlation_15_MJuse.eps correlation_15_MJuse.png
convert correlation_15_MJdep.eps correlation_15_MJdep.png
convert correlation_15_MJonset.eps correlation_15_MJonset.png
convert correlation_15_TimeUsed.eps correlation_15_TimeUsed.png
convert correlation_15_CT_RT.eps correlation_15_CT_RT.png
convert correlation_15_INTER_RT.eps correlation_15_INTER_RT.png
convert correlation_15_INTER_ACC.eps correlation_15_INTER_ACC.png

convert correlation_16_age.eps correlation_16_age.png
convert correlation_16_ToT_Drink7day.eps correlation_16_ToT_Drink7day.png
convert correlation_16_sex.eps correlation_16_sex.png
convert correlation_16_Num_Days_Drink7day.eps correlation_16_Num_Days_Drink7day.png
convert correlation_16_SmoHistory.eps correlation_16_SmoHistory.png
convert correlation_16_StillSmoking.eps correlation_16_StillSmoking.png
convert correlation_16_QuitYears.eps correlation_16_QuitYears.png
convert correlation_16_SmokedYears.eps correlation_16_SmokedYears.png
convert correlation_16_MJuse.eps correlation_16_MJuse.png
convert correlation_16_MJdep.eps correlation_16_MJdep.png
convert correlation_16_MJonset.eps correlation_16_MJonset.png
convert correlation_16_TimeUsed.eps correlation_16_TimeUsed.png
convert correlation_16_CT_RT.eps correlation_16_CT_RT.png
convert correlation_16_INTER_RT.eps correlation_16_INTER_RT.png
convert correlation_16_INTER_ACC.eps correlation_16_INTER_ACC.png

convert correlation_17_age.eps correlation_17_age.png
convert correlation_17_ToT_Drink7day.eps correlation_17_ToT_Drink7day.png
convert correlation_17_sex.eps correlation_17_sex.png
convert correlation_17_Num_Days_Drink7day.eps correlation_17_Num_Days_Drink7day.png
convert correlation_17_SmoHistory.eps correlation_17_SmoHistory.png
convert correlation_17_StillSmoking.eps correlation_17_StillSmoking.png
convert correlation_17_QuitYears.eps correlation_17_QuitYears.png
convert correlation_17_SmokedYears.eps correlation_17_SmokedYears.png
convert correlation_17_MJuse.eps correlation_17_MJuse.png
convert correlation_17_MJdep.eps correlation_17_MJdep.png
convert correlation_17_MJonset.eps correlation_17_MJonset.png
convert correlation_17_TimeUsed.eps correlation_17_TimeUsed.png
convert correlation_17_CT_RT.eps correlation_17_CT_RT.png
convert correlation_17_INTER_RT.eps correlation_17_INTER_RT.png
convert correlation_17_INTER_ACC.eps correlation_17_INTER_ACC.png

convert correlation_18_age.eps correlation_18_age.png
convert correlation_18_ToT_Drink7day.eps correlation_18_ToT_Drink7day.png
convert correlation_18_sex.eps correlation_18_sex.png
convert correlation_18_Num_Days_Drink7day.eps correlation_18_Num_Days_Drink7day.png
convert correlation_18_SmoHistory.eps correlation_18_SmoHistory.png
convert correlation_18_StillSmoking.eps correlation_18_StillSmoking.png
convert correlation_18_QuitYears.eps correlation_18_QuitYears.png
convert correlation_18_SmokedYears.eps correlation_18_SmokedYears.png
convert correlation_18_MJuse.eps correlation_18_MJuse.png
convert correlation_18_MJdep.eps correlation_18_MJdep.png
convert correlation_18_MJonset.eps correlation_18_MJonset.png
convert correlation_18_TimeUsed.eps correlation_18_TimeUsed.png
convert correlation_18_CT_RT.eps correlation_18_CT_RT.png
convert correlation_18_INTER_RT.eps correlation_18_INTER_RT.png
convert correlation_18_INTER_ACC.eps correlation_18_INTER_ACC.png

convert correlation_19_age.eps correlation_19_age.png
convert correlation_19_ToT_Drink7day.eps correlation_19_ToT_Drink7day.png
convert correlation_19_sex.eps correlation_19_sex.png
convert correlation_19_Num_Days_Drink7day.eps correlation_19_Num_Days_Drink7day.png
convert correlation_19_SmoHistory.eps correlation_19_SmoHistory.png
convert correlation_19_StillSmoking.eps correlation_19_StillSmoking.png
convert correlation_19_QuitYears.eps correlation_19_QuitYears.png
convert correlation_19_SmokedYears.eps correlation_19_SmokedYears.png
convert correlation_19_MJuse.eps correlation_19_MJuse.png
convert correlation_19_MJdep.eps correlation_19_MJdep.png
convert correlation_19_MJonset.eps correlation_19_MJonset.png
convert correlation_19_TimeUsed.eps correlation_19_TimeUsed.png
convert correlation_19_CT_RT.eps correlation_19_CT_RT.png
convert correlation_19_INTER_RT.eps correlation_19_INTER_RT.png
convert correlation_19_INTER_ACC.eps correlation_19_INTER_ACC.png

convert correlation_20_age.eps correlation_20_age.png
convert correlation_20_ToT_Drink7day.eps correlation_20_ToT_Drink7day.png
convert correlation_20_sex.eps correlation_20_sex.png
convert correlation_20_Num_Days_Drink7day.eps correlation_20_Num_Days_Drink7day.png
convert correlation_20_SmoHistory.eps correlation_20_SmoHistory.png
convert correlation_20_StillSmoking.eps correlation_20_StillSmoking.png
convert correlation_20_QuitYears.eps correlation_20_QuitYears.png
convert correlation_20_SmokedYears.eps correlation_20_SmokedYears.png
convert correlation_20_MJuse.eps correlation_20_MJuse.png
convert correlation_20_MJdep.eps correlation_20_MJdep.png
convert correlation_20_MJonset.eps correlation_20_MJonset.png
convert correlation_20_TimeUsed.eps correlation_20_TimeUsed.png
convert correlation_20_CT_RT.eps correlation_20_CT_RT.png
convert correlation_20_INTER_RT.eps correlation_20_INTER_RT.png
convert correlation_20_INTER_ACC.eps correlation_20_INTER_ACC.png

convert correlation_21_age.eps correlation_21_age.png
convert correlation_21_ToT_Drink7day.eps correlation_21_ToT_Drink7day.png
convert correlation_21_sex.eps correlation_21_sex.png
convert correlation_21_Num_Days_Drink7day.eps correlation_21_Num_Days_Drink7day.png
convert correlation_21_SmoHistory.eps correlation_21_SmoHistory.png
convert correlation_21_StillSmoking.eps correlation_21_StillSmoking.png
convert correlation_21_QuitYears.eps correlation_21_QuitYears.png
convert correlation_21_SmokedYears.eps correlation_21_SmokedYears.png
convert correlation_21_MJuse.eps correlation_21_MJuse.png
convert correlation_21_MJdep.eps correlation_21_MJdep.png
convert correlation_21_MJonset.eps correlation_21_MJonset.png
convert correlation_21_TimeUsed.eps correlation_21_TimeUsed.png
convert correlation_21_CT_RT.eps correlation_21_CT_RT.png
convert correlation_21_INTER_RT.eps correlation_21_INTER_RT.png
convert correlation_21_INTER_ACC.eps correlation_21_INTER_ACC.png

convert correlation_22_age.eps correlation_22_age.png
convert correlation_22_ToT_Drink7day.eps correlation_22_ToT_Drink7day.png
convert correlation_22_sex.eps correlation_22_sex.png
convert correlation_22_Num_Days_Drink7day.eps correlation_22_Num_Days_Drink7day.png
convert correlation_22_SmoHistory.eps correlation_22_SmoHistory.png
convert correlation_22_StillSmoking.eps correlation_22_StillSmoking.png
convert correlation_22_QuitYears.eps correlation_22_QuitYears.png
convert correlation_22_SmokedYears.eps correlation_22_SmokedYears.png
convert correlation_22_MJuse.eps correlation_22_MJuse.png
convert correlation_22_MJdep.eps correlation_22_MJdep.png
convert correlation_22_MJonset.eps correlation_22_MJonset.png
convert correlation_22_TimeUsed.eps correlation_22_TimeUsed.png
convert correlation_22_CT_RT.eps correlation_22_CT_RT.png
convert correlation_22_INTER_RT.eps correlation_22_INTER_RT.png
convert correlation_22_INTER_ACC.eps correlation_22_INTER_ACC.png

convert correlation_23_age.eps correlation_23_age.png
convert correlation_23_ToT_Drink7day.eps correlation_23_ToT_Drink7day.png
convert correlation_23_sex.eps correlation_23_sex.png
convert correlation_23_Num_Days_Drink7day.eps correlation_23_Num_Days_Drink7day.png
convert correlation_23_SmoHistory.eps correlation_23_SmoHistory.png
convert correlation_23_StillSmoking.eps correlation_23_StillSmoking.png
convert correlation_23_QuitYears.eps correlation_23_QuitYears.png
convert correlation_23_SmokedYears.eps correlation_23_SmokedYears.png
convert correlation_23_MJuse.eps correlation_23_MJuse.png
convert correlation_23_MJdep.eps correlation_23_MJdep.png
convert correlation_23_MJonset.eps correlation_23_MJonset.png
convert correlation_23_TimeUsed.eps correlation_23_TimeUsed.png
convert correlation_23_CT_RT.eps correlation_23_CT_RT.png
convert correlation_23_INTER_RT.eps correlation_23_INTER_RT.png
convert correlation_23_INTER_ACC.eps correlation_23_INTER_ACC.png

convert correlation_24_age.eps correlation_24_age.png
convert correlation_24_ToT_Drink7day.eps correlation_24_ToT_Drink7day.png
convert correlation_24_sex.eps correlation_24_sex.png
convert correlation_24_Num_Days_Drink7day.eps correlation_24_Num_Days_Drink7day.png
convert correlation_24_SmoHistory.eps correlation_24_SmoHistory.png
convert correlation_24_StillSmoking.eps correlation_24_StillSmoking.png
convert correlation_24_QuitYears.eps correlation_24_QuitYears.png
convert correlation_24_SmokedYears.eps correlation_24_SmokedYears.png
convert correlation_24_MJuse.eps correlation_24_MJuse.png
convert correlation_24_MJdep.eps correlation_24_MJdep.png
convert correlation_24_MJonset.eps correlation_24_MJonset.png
convert correlation_24_TimeUsed.eps correlation_24_TimeUsed.png
convert correlation_24_CT_RT.eps correlation_24_CT_RT.png
convert correlation_24_INTER_RT.eps correlation_24_INTER_RT.png
convert correlation_24_INTER_ACC.eps correlation_24_INTER_ACC.png

convert correlation_25_age.eps correlation_25_age.png
convert correlation_25_ToT_Drink7day.eps correlation_25_ToT_Drink7day.png
convert correlation_25_sex.eps correlation_25_sex.png
convert correlation_25_Num_Days_Drink7day.eps correlation_25_Num_Days_Drink7day.png
convert correlation_25_SmoHistory.eps correlation_25_SmoHistory.png
convert correlation_25_StillSmoking.eps correlation_25_StillSmoking.png
convert correlation_25_QuitYears.eps correlation_25_QuitYears.png
convert correlation_25_SmokedYears.eps correlation_25_SmokedYears.png
convert correlation_25_MJuse.eps correlation_25_MJuse.png
convert correlation_25_MJdep.eps correlation_25_MJdep.png
convert correlation_25_MJonset.eps correlation_25_MJonset.png
convert correlation_25_TimeUsed.eps correlation_25_TimeUsed.png
convert correlation_25_CT_RT.eps correlation_25_CT_RT.png
convert correlation_25_INTER_RT.eps correlation_25_INTER_RT.png
convert correlation_25_INTER_ACC.eps correlation_25_INTER_ACC.png

convert correlation_26_age.eps correlation_26_age.png
convert correlation_26_ToT_Drink7day.eps correlation_26_ToT_Drink7day.png
convert correlation_26_sex.eps correlation_26_sex.png
convert correlation_26_Num_Days_Drink7day.eps correlation_26_Num_Days_Drink7day.png
convert correlation_26_SmoHistory.eps correlation_26_SmoHistory.png
convert correlation_26_StillSmoking.eps correlation_26_StillSmoking.png
convert correlation_26_QuitYears.eps correlation_26_QuitYears.png
convert correlation_26_SmokedYears.eps correlation_26_SmokedYears.png
convert correlation_26_MJuse.eps correlation_26_MJuse.png
convert correlation_26_MJdep.eps correlation_26_MJdep.png
convert correlation_26_MJonset.eps correlation_26_MJonset.png
convert correlation_26_TimeUsed.eps correlation_26_TimeUsed.png
convert correlation_26_CT_RT.eps correlation_26_CT_RT.png
convert correlation_26_INTER_RT.eps correlation_26_INTER_RT.png
convert correlation_26_INTER_ACC.eps correlation_26_INTER_ACC.png

convert correlation_27_age.eps correlation_27_age.png
convert correlation_27_ToT_Drink7day.eps correlation_27_ToT_Drink7day.png
convert correlation_27_sex.eps correlation_27_sex.png
convert correlation_27_Num_Days_Drink7day.eps correlation_27_Num_Days_Drink7day.png
convert correlation_27_SmoHistory.eps correlation_27_SmoHistory.png
convert correlation_27_StillSmoking.eps correlation_27_StillSmoking.png
convert correlation_27_QuitYears.eps correlation_27_QuitYears.png
convert correlation_27_SmokedYears.eps correlation_27_SmokedYears.png
convert correlation_27_MJuse.eps correlation_27_MJuse.png
convert correlation_27_MJdep.eps correlation_27_MJdep.png
convert correlation_27_MJonset.eps correlation_27_MJonset.png
convert correlation_27_TimeUsed.eps correlation_27_TimeUsed.png
convert correlation_27_CT_RT.eps correlation_27_CT_RT.png
convert correlation_27_INTER_RT.eps correlation_27_INTER_RT.png
convert correlation_27_INTER_ACC.eps correlation_27_INTER_ACC.png

convert correlation_28_age.eps correlation_28_age.png
convert correlation_28_ToT_Drink7day.eps correlation_28_ToT_Drink7day.png
convert correlation_28_sex.eps correlation_28_sex.png
convert correlation_28_Num_Days_Drink7day.eps correlation_28_Num_Days_Drink7day.png
convert correlation_28_SmoHistory.eps correlation_28_SmoHistory.png
convert correlation_28_StillSmoking.eps correlation_28_StillSmoking.png
convert correlation_28_QuitYears.eps correlation_28_QuitYears.png
convert correlation_28_SmokedYears.eps correlation_28_SmokedYears.png
convert correlation_28_MJuse.eps correlation_28_MJuse.png
convert correlation_28_MJdep.eps correlation_28_MJdep.png
convert correlation_28_MJonset.eps correlation_28_MJonset.png
convert correlation_28_TimeUsed.eps correlation_28_TimeUsed.png
convert correlation_28_CT_RT.eps correlation_28_CT_RT.png
convert correlation_28_INTER_RT.eps correlation_28_INTER_RT.png
convert correlation_28_INTER_ACC.eps correlation_28_INTER_ACC.png

convert correlation_29_age.eps correlation_29_age.png
convert correlation_29_ToT_Drink7day.eps correlation_29_ToT_Drink7day.png
convert correlation_29_sex.eps correlation_29_sex.png
convert correlation_29_Num_Days_Drink7day.eps correlation_29_Num_Days_Drink7day.png
convert correlation_29_SmoHistory.eps correlation_29_SmoHistory.png
convert correlation_29_StillSmoking.eps correlation_29_StillSmoking.png
convert correlation_29_QuitYears.eps correlation_29_QuitYears.png
convert correlation_29_SmokedYears.eps correlation_29_SmokedYears.png
convert correlation_29_MJuse.eps correlation_29_MJuse.png
convert correlation_29_MJdep.eps correlation_29_MJdep.png
convert correlation_29_MJonset.eps correlation_29_MJonset.png
convert correlation_29_TimeUsed.eps correlation_29_TimeUsed.png
convert correlation_29_CT_RT.eps correlation_29_CT_RT.png
convert correlation_29_INTER_RT.eps correlation_29_INTER_RT.png
convert correlation_29_INTER_ACC.eps correlation_29_INTER_ACC.png

convert correlation_30_age.eps correlation_30_age.png
convert correlation_30_ToT_Drink7day.eps correlation_30_ToT_Drink7day.png
convert correlation_30_sex.eps correlation_30_sex.png
convert correlation_30_Num_Days_Drink7day.eps correlation_30_Num_Days_Drink7day.png
convert correlation_30_SmoHistory.eps correlation_30_SmoHistory.png
convert correlation_30_StillSmoking.eps correlation_30_StillSmoking.png
convert correlation_30_QuitYears.eps correlation_30_QuitYears.png
convert correlation_30_SmokedYears.eps correlation_30_SmokedYears.png
convert correlation_30_MJuse.eps correlation_30_MJuse.png
convert correlation_30_MJdep.eps correlation_30_MJdep.png
convert correlation_30_MJonset.eps correlation_30_MJonset.png
convert correlation_30_TimeUsed.eps correlation_30_TimeUsed.png
convert correlation_30_CT_RT.eps correlation_30_CT_RT.png
convert correlation_30_INTER_RT.eps correlation_30_INTER_RT.png
convert correlation_30_INTER_ACC.eps correlation_30_INTER_ACC.png

convert correlation_31_age.eps correlation_31_age.png
convert correlation_31_ToT_Drink7day.eps correlation_31_ToT_Drink7day.png
convert correlation_31_sex.eps correlation_31_sex.png
convert correlation_31_Num_Days_Drink7day.eps correlation_31_Num_Days_Drink7day.png
convert correlation_31_SmoHistory.eps correlation_31_SmoHistory.png
convert correlation_31_StillSmoking.eps correlation_31_StillSmoking.png
convert correlation_31_QuitYears.eps correlation_31_QuitYears.png
convert correlation_31_SmokedYears.eps correlation_31_SmokedYears.png
convert correlation_31_MJuse.eps correlation_31_MJuse.png
convert correlation_31_MJdep.eps correlation_31_MJdep.png
convert correlation_31_MJonset.eps correlation_31_MJonset.png
convert correlation_31_TimeUsed.eps correlation_31_TimeUsed.png
convert correlation_31_CT_RT.eps correlation_31_CT_RT.png
convert correlation_31_INTER_RT.eps correlation_31_INTER_RT.png
convert correlation_31_INTER_ACC.eps correlation_31_INTER_ACC.png

convert correlation_32_age.eps correlation_32_age.png
convert correlation_32_ToT_Drink7day.eps correlation_32_ToT_Drink7day.png
convert correlation_32_sex.eps correlation_32_sex.png
convert correlation_32_Num_Days_Drink7day.eps correlation_32_Num_Days_Drink7day.png
convert correlation_32_SmoHistory.eps correlation_32_SmoHistory.png
convert correlation_32_StillSmoking.eps correlation_32_StillSmoking.png
convert correlation_32_QuitYears.eps correlation_32_QuitYears.png
convert correlation_32_SmokedYears.eps correlation_32_SmokedYears.png
convert correlation_32_MJuse.eps correlation_32_MJuse.png
convert correlation_32_MJdep.eps correlation_32_MJdep.png
convert correlation_32_MJonset.eps correlation_32_MJonset.png
convert correlation_32_TimeUsed.eps correlation_32_TimeUsed.png
convert correlation_32_CT_RT.eps correlation_32_CT_RT.png
convert correlation_32_INTER_RT.eps correlation_32_INTER_RT.png
convert correlation_32_INTER_ACC.eps correlation_32_INTER_ACC.png

convert correlation_33_age.eps correlation_33_age.png
convert correlation_33_ToT_Drink7day.eps correlation_33_ToT_Drink7day.png
convert correlation_33_sex.eps correlation_33_sex.png
convert correlation_33_Num_Days_Drink7day.eps correlation_33_Num_Days_Drink7day.png
convert correlation_33_SmoHistory.eps correlation_33_SmoHistory.png
convert correlation_33_StillSmoking.eps correlation_33_StillSmoking.png
convert correlation_33_QuitYears.eps correlation_33_QuitYears.png
convert correlation_33_SmokedYears.eps correlation_33_SmokedYears.png
convert correlation_33_MJuse.eps correlation_33_MJuse.png
convert correlation_33_MJdep.eps correlation_33_MJdep.png
convert correlation_33_MJonset.eps correlation_33_MJonset.png
convert correlation_33_TimeUsed.eps correlation_33_TimeUsed.png
convert correlation_33_CT_RT.eps correlation_33_CT_RT.png
convert correlation_33_INTER_RT.eps correlation_33_INTER_RT.png
convert correlation_33_INTER_ACC.eps correlation_33_INTER_ACC.png

convert correlation_34_age.eps correlation_34_age.png
convert correlation_34_ToT_Drink7day.eps correlation_34_ToT_Drink7day.png
convert correlation_34_sex.eps correlation_34_sex.png
convert correlation_34_Num_Days_Drink7day.eps correlation_34_Num_Days_Drink7day.png
convert correlation_34_SmoHistory.eps correlation_34_SmoHistory.png
convert correlation_34_StillSmoking.eps correlation_34_StillSmoking.png
convert correlation_34_QuitYears.eps correlation_34_QuitYears.png
convert correlation_34_SmokedYears.eps correlation_34_SmokedYears.png
convert correlation_34_MJuse.eps correlation_34_MJuse.png
convert correlation_34_MJdep.eps correlation_34_MJdep.png
convert correlation_34_MJonset.eps correlation_34_MJonset.png
convert correlation_34_TimeUsed.eps correlation_34_TimeUsed.png
convert correlation_34_CT_RT.eps correlation_34_CT_RT.png
convert correlation_34_INTER_RT.eps correlation_34_INTER_RT.png
convert correlation_34_INTER_ACC.eps correlation_34_INTER_ACC.png

convert correlation_35_age.eps correlation_35_age.png
convert correlation_35_ToT_Drink7day.eps correlation_35_ToT_Drink7day.png
convert correlation_35_sex.eps correlation_35_sex.png
convert correlation_35_Num_Days_Drink7day.eps correlation_35_Num_Days_Drink7day.png
convert correlation_35_SmoHistory.eps correlation_35_SmoHistory.png
convert correlation_35_StillSmoking.eps correlation_35_StillSmoking.png
convert correlation_35_QuitYears.eps correlation_35_QuitYears.png
convert correlation_35_SmokedYears.eps correlation_35_SmokedYears.png
convert correlation_35_MJuse.eps correlation_35_MJuse.png
convert correlation_35_MJdep.eps correlation_35_MJdep.png
convert correlation_35_MJonset.eps correlation_35_MJonset.png
convert correlation_35_TimeUsed.eps correlation_35_TimeUsed.png
convert correlation_35_CT_RT.eps correlation_35_CT_RT.png
convert correlation_35_INTER_RT.eps correlation_35_INTER_RT.png
convert correlation_35_INTER_ACC.eps correlation_35_INTER_ACC.png

convert correlation_36_age.eps correlation_36_age.png
convert correlation_36_ToT_Drink7day.eps correlation_36_ToT_Drink7day.png
convert correlation_36_sex.eps correlation_36_sex.png
convert correlation_36_Num_Days_Drink7day.eps correlation_36_Num_Days_Drink7day.png
convert correlation_36_SmoHistory.eps correlation_36_SmoHistory.png
convert correlation_36_StillSmoking.eps correlation_36_StillSmoking.png
convert correlation_36_QuitYears.eps correlation_36_QuitYears.png
convert correlation_36_SmokedYears.eps correlation_36_SmokedYears.png
convert correlation_36_MJuse.eps correlation_36_MJuse.png
convert correlation_36_MJdep.eps correlation_36_MJdep.png
convert correlation_36_MJonset.eps correlation_36_MJonset.png
convert correlation_36_TimeUsed.eps correlation_36_TimeUsed.png
convert correlation_36_CT_RT.eps correlation_36_CT_RT.png
convert correlation_36_INTER_RT.eps correlation_36_INTER_RT.png
convert correlation_36_INTER_ACC.eps correlation_36_INTER_ACC.png


# convert correlation_16_age.eps correlation_16_age.png
# convert correlation_16_ToT_Drink7day.eps correlation_16_ToT_Drink7day.png
# convert correlation_16_sex.eps correlation_16_sex.png
# convert correlation_16_Num_Days_Drink7day.eps correlation_16_Num_Days_Drink7day.png
# convert correlation_16_SmoHistory.eps correlation_16_SmoHistory.png
# convert correlation_16_StillSmoking.eps correlation_16_StillSmoking.png
# convert correlation_16_QuitYears.eps correlation_16_QuitYears.png
# convert correlation_16_SmokedYears.eps correlation_16_SmokedYears.png
# convert correlation_16_INTER_ACC.eps correlation_16_INTER_ACC.png
# convert correlation_17_age.eps correlation_17_age.png
# convert correlation_17_ToT_Drink7day.eps correlation_17_ToT_Drink7day.png
# convert correlation_17_sex.eps correlation_17_sex.png
# convert correlation_17_Num_Days_Drink7day.eps correlation_17_Num_Days_Drink7day.png
# convert correlation_17_SmoHistory.eps correlation_17_SmoHistory.png
# convert correlation_17_StillSmoking.eps correlation_17_StillSmoking.png
# convert correlation_17_QuitYears.eps correlation_17_QuitYears.png
# convert correlation_17_SmokedYears.eps correlation_17_SmokedYears.png
# convert correlation_17_INTER_ACC.eps correlation_17_INTER_ACC.png
# convert correlation_18_age.eps correlation_18_age.png
# convert correlation_18_ToT_Drink7day.eps correlation_18_ToT_Drink7day.png
# convert correlation_18_sex.eps correlation_18_sex.png
# convert correlation_18_Num_Days_Drink7day.eps correlation_18_Num_Days_Drink7day.png
# convert correlation_18_SmoHistory.eps correlation_18_SmoHistory.png
# convert correlation_18_StillSmoking.eps correlation_18_StillSmoking.png
# convert correlation_18_QuitYears.eps correlation_18_QuitYears.png
# convert correlation_18_SmokedYears.eps correlation_18_SmokedYears.png
# convert correlation_18_INTER_ACC.eps correlation_18_INTER_ACC.png
# convert correlation_19_age.eps correlation_19_age.png
# convert correlation_19_ToT_Drink7day.eps correlation_19_ToT_Drink7day.png
# convert correlation_19_sex.eps correlation_19_sex.png
# convert correlation_19_Num_Days_Drink7day.eps correlation_19_Num_Days_Drink7day.png
# convert correlation_19_SmoHistory.eps correlation_19_SmoHistory.png
# convert correlation_19_StillSmoking.eps correlation_19_StillSmoking.png
# convert correlation_19_QuitYears.eps correlation_19_QuitYears.png
# convert correlation_19_SmokedYears.eps correlation_19_SmokedYears.png
# convert correlation_19_INTER_ACC.eps correlation_19_INTER_ACC.png
# convert correlation_21_ToT_Drink7day.eps correlation_21_ToT_Drink7day.png
# convert correlation_21_sex.eps correlation_21_sex.png
# convert correlation_21_Num_Days_Drink7day.eps correlation_21_Num_Days_Drink7day.png
# convert correlation_21_SmoHistory.eps correlation_21_SmoHistory.png
# convert correlation_21_StillSmoking.eps correlation_21_StillSmoking.png
# convert correlation_21_QuitYears.eps correlation_21_QuitYears.png
# convert correlation_21_SmokedYears.eps correlation_21_SmokedYears.png
# convert correlation_21_INTER_ACC.eps correlation_21_INTER_ACC.png
# convert correlation_21_age.eps correlation_21_age.png
# convert correlation_21_ToT_Drink7day.eps correlation_21_ToT_Drink7day.png
# convert correlation_21_sex.eps correlation_21_sex.png
# convert correlation_21_Num_Days_Drink7day.eps correlation_21_Num_Days_Drink7day.png
# convert correlation_21_SmoHistory.eps correlation_21_SmoHistory.png
# convert correlation_21_StillSmoking.eps correlation_21_StillSmoking.png
# convert correlation_21_QuitYears.eps correlation_21_QuitYears.png
# convert correlation_21_PP.eps correlation_21_PP.png
# convert correlation_22_age.eps correlation_22_age.png
# convert correlation_22_ToT_Drink7day.eps correlation_22_ToT_Drink7day.png
# convert correlation_22_sex.eps correlation_22_sex.png
# convert correlation_22_Num_Days_Drink7day.eps correlation_22_Num_Days_Drink7day.png
# convert correlation_22_SmoHistory.eps correlation_22_SmoHistory.png
# convert correlation_22_StillSmoking.eps correlation_22_StillSmoking.png
# convert correlation_22_QuitYears.eps correlation_22_QuitYears.png
# convert correlation_22_PP.eps correlation_22_PP.png
# convert correlation_23_age.eps correlation_23_age.png
# convert correlation_23_ToT_Drink7day.eps correlation_23_ToT_Drink7day.png
# convert correlation_23_sex.eps correlation_23_sex.png
# convert correlation_23_Num_Days_Drink7day.eps correlation_23_Num_Days_Drink7day.png
# convert correlation_23_SmoHistory.eps correlation_23_SmoHistory.png
# convert correlation_23_StillSmoking.eps correlation_23_StillSmoking.png
# convert correlation_23_QuitYears.eps correlation_23_QuitYears.png
# convert correlation_23_PP.eps correlation_23_PP.png
# convert correlation_24_age.eps correlation_24_age.png
# convert correlation_24_ToT_Drink7day.eps correlation_24_ToT_Drink7day.png
# convert correlation_24_sex.eps correlation_24_sex.png
# convert correlation_24_Num_Days_Drink7day.eps correlation_24_Num_Days_Drink7day.png
# convert correlation_24_SmoHistory.eps correlation_24_SmoHistory.png
# convert correlation_24_StillSmoking.eps correlation_24_StillSmoking.png
# convert correlation_24_QuitYears.eps correlation_24_QuitYears.png
# convert correlation_24_PP.eps correlation_24_PP.png
# convert correlation_25_age.eps correlation_25_age.png
# convert correlation_25_ToT_Drink7day.eps correlation_25_ToT_Drink7day.png
# convert correlation_25_sex.eps correlation_25_sex.png
# convert correlation_25_Num_Days_Drink7day.eps correlation_25_Num_Days_Drink7day.png
# convert correlation_25_SmoHistory.eps correlation_25_SmoHistory.png
# convert correlation_25_StillSmoking.eps correlation_25_StillSmoking.png
# convert correlation_25_QuitYears.eps correlation_25_QuitYears.png
# convert correlation_25_PP.eps correlation_25_PP.png
# convert correlation_26_age.eps correlation_26_age.png
# convert correlation_26_ToT_Drink7day.eps correlation_26_ToT_Drink7day.png
# convert correlation_26_sex.eps correlation_26_sex.png
# convert correlation_26_Num_Days_Drink7day.eps correlation_26_Num_Days_Drink7day.png
# convert correlation_26_SmoHistory.eps correlation_26_SmoHistory.png
# convert correlation_26_StillSmoking.eps correlation_26_StillSmoking.png
# convert correlation_26_QuitYears.eps correlation_26_QuitYears.png
# convert correlation_26_PP.eps correlation_26_PP.png
# convert correlation_27_age.eps correlation_27_age.png
# convert correlation_27_ToT_Drink7day.eps correlation_27_ToT_Drink7day.png
# convert correlation_27_sex.eps correlation_27_sex.png
# convert correlation_27_Num_Days_Drink7day.eps correlation_27_Num_Days_Drink7day.png
# convert correlation_27_SmoHistory.eps correlation_27_SmoHistory.png
# convert correlation_27_StillSmoking.eps correlation_27_StillSmoking.png
# convert correlation_27_QuitYears.eps correlation_27_QuitYears.png
# convert correlation_27_PP.eps correlation_27_PP.png
# convert correlation_28_age.eps correlation_28_age.png
# convert correlation_28_ToT_Drink7day.eps correlation_28_ToT_Drink7day.png
# convert correlation_28_sex.eps correlation_28_sex.png
# convert correlation_28_Num_Days_Drink7day.eps correlation_28_Num_Days_Drink7day.png
# convert correlation_28_SmoHistory.eps correlation_28_SmoHistory.png
# convert correlation_28_StillSmoking.eps correlation_28_StillSmoking.png
# convert correlation_28_QuitYears.eps correlation_28_QuitYears.png
# convert correlation_28_PP.eps correlation_28_PP.png
# convert correlation_29_age.eps correlation_29_age.png
# convert correlation_29_ToT_Drink7day.eps correlation_29_ToT_Drink7day.png
# convert correlation_29_sex.eps correlation_29_sex.png
# convert correlation_29_Num_Days_Drink7day.eps correlation_29_Num_Days_Drink7day.png
# convert correlation_29_SmoHistory.eps correlation_29_SmoHistory.png
# convert correlation_29_StillSmoking.eps correlation_29_StillSmoking.png
# convert correlation_29_QuitYears.eps correlation_29_QuitYears.png
# convert correlation_29_PP.eps correlation_29_PP.png
# convert correlation_31_ToT_Drink7day.eps correlation_31_ToT_Drink7day.png
# convert correlation_31_sex.eps correlation_31_sex.png
# convert correlation_31_Num_Days_Drink7day.eps correlation_31_Num_Days_Drink7day.png
# convert correlation_31_SmoHistory.eps correlation_31_SmoHistory.png
# convert correlation_31_StillSmoking.eps correlation_31_StillSmoking.png
# convert correlation_31_QuitYears.eps correlation_31_QuitYears.png
# convert correlation_31_PP.eps correlation_31_PP.png
# convert correlation_31_age.eps correlation_33_age.png
# convert correlation_31_ToT_Drink7day.eps correlation_31_ToT_Drink7day.png
# convert correlation_31_sex.eps correlation_31_sex.png
# convert correlation_31_Num_Days_Drink7day.eps correlation_31_Num_Days_Drink7day.png
# convert correlation_31_SmoHistory.eps correlation_31_SmoHistory.png
# convert correlation_31_StillSmoking.eps correlation_31_StillSmoking.png
# convert correlation_31_QuitYears.eps correlation_31_QuitYears.png
# convert correlation_31_PP.eps correlation_31_PP.png
# convert correlation_32_age.eps correlation_32_age.png
# convert correlation_32_ToT_Drink7day.eps correlation_32_ToT_Drink7day.png
# convert correlation_32_sex.eps correlation_32_sex.png
# convert correlation_32_Num_Days_Drink7day.eps correlation_32_Num_Days_Drink7day.png
# convert correlation_32_SmoHistory.eps correlation_32_SmoHistory.png
# convert correlation_32_StillSmoking.eps correlation_32_StillSmoking.png
# convert correlation_32_QuitYears.eps correlation_32_QuitYears.png
# convert correlation_32_PP.eps correlation_32_PP.png
# convert correlation_33_age.eps correlation_33_age.png
# convert correlation_33_ToT_Drink7day.eps correlation_33_ToT_Drink7day.png
# convert correlation_33_sex.eps correlation_33_sex.png
# convert correlation_33_Num_Days_Drink7day.eps correlation_33_Num_Days_Drink7day.png
# convert correlation_33_SmoHistory.eps correlation_33_SmoHistory.png
# convert correlation_33_StillSmoking.eps correlation_33_StillSmoking.png
# convert correlation_33_QuitYears.eps correlation_33_QuitYears.png
# convert correlation_33_PP.eps correlation_33_PP.png
# convert correlation_34_age.eps correlation_34_age.png
# convert correlation_34_ToT_Drink7day.eps correlation_34_ToT_Drink7day.png
# convert correlation_34_sex.eps correlation_34_sex.png
# convert correlation_34_Num_Days_Drink7day.eps correlation_34_Num_Days_Drink7day.png
# convert correlation_34_SmoHistory.eps correlation_34_SmoHistory.png
# convert correlation_34_StillSmoking.eps correlation_34_StillSmoking.png
# convert correlation_34_QuitYears.eps correlation_34_QuitYears.png
# convert correlation_34_PP.eps correlation_34_PP.png
# convert correlation_35_age.eps correlation_35_age.png
# convert correlation_35_ToT_Drink7day.eps correlation_35_ToT_Drink7day.png
# convert correlation_35_sex.eps correlation_35_sex.png
# convert correlation_35_Num_Days_Drink7day.eps correlation_35_Num_Days_Drink7day.png
# convert correlation_35_SmoHistory.eps correlation_35_SmoHistory.png
# convert correlation_35_StillSmoking.eps correlation_35_StillSmoking.png
# convert correlation_35_QuitYears.eps correlation_35_QuitYears.png
# convert correlation_35_PP.eps correlation_35_PP.png
# convert correlation_36_age.eps correlation_36_age.png
# convert correlation_36_ToT_Drink7day.eps correlation_36_ToT_Drink7day.png
# convert correlation_36_sex.eps correlation_36_sex.png
# convert correlation_36_Num_Days_Drink7day.eps correlation_36_Num_Days_Drink7day.png
# convert correlation_36_SmoHistory.eps correlation_36_SmoHistory.png
# convert correlation_36_StillSmoking.eps correlation_36_StillSmoking.png
# convert correlation_36_QuitYears.eps correlation_36_QuitYears.png
# convert correlation_36_PP.eps correlation_36_PP.png
# convert correlation_37_age.eps correlation_37_age.png
# convert correlation_37_ToT_Drink7day.eps correlation_37_ToT_Drink7day.png
# convert correlation_37_sex.eps correlation_37_sex.png
# convert correlation_37_Num_Days_Drink7day.eps correlation_37_Num_Days_Drink7day.png
# convert correlation_37_SmoHistory.eps correlation_37_SmoHistory.png
# convert correlation_37_StillSmoking.eps correlation_37_StillSmoking.png
# convert correlation_37_QuitYears.eps correlation_37_QuitYears.png
# convert correlation_37_PP.eps correlation_37_PP.png
# convert correlation_38_age.eps correlation_38_age.png
# convert correlation_38_ToT_Drink7day.eps correlation_38_ToT_Drink7day.png
# convert correlation_38_sex.eps correlation_38_sex.png
# convert correlation_38_Num_Days_Drink7day.eps correlation_38_Num_Days_Drink7day.png
# convert correlation_38_SmoHistory.eps correlation_38_SmoHistory.png
# convert correlation_38_StillSmoking.eps correlation_38_StillSmoking.png
# convert correlation_38_QuitYears.eps correlation_38_QuitYears.png
# convert correlation_38_PP.eps correlation_38_PP.png
# convert correlation_39_age.eps correlation_39_age.png
# convert correlation_39_ToT_Drink7day.eps correlation_39_ToT_Drink7day.png
# convert correlation_39_sex.eps correlation_39_sex.png
# convert correlation_39_Num_Days_Drink7day.eps correlation_39_Num_Days_Drink7day.png
# convert correlation_39_SmoHistory.eps correlation_39_SmoHistory.png
# convert correlation_39_StillSmoking.eps correlation_39_StillSmoking.png
# convert correlation_39_QuitYears.eps correlation_39_QuitYears.png
# convert correlation_39_PP.eps correlation_39_PP.png